from .planning_agent import planning_agent
from .decision_agent import decision_agent
from .tools import (
    create_specification_book_func,
    create_project_tasks_func,
    send_notification_func
)
from langchain_core.messages import HumanMessage, SystemMessage
from app.core.db import get_database
from datetime import datetime, timedelta, timezone
from bson import ObjectId
import json
import re
import random
import string


async def generate_and_assign_tasks(project_id: str, project_name: str, spec_content: str):
    """
    Generate tasks in French. No auto-assignment — manager assigns manually in Kanban.
    """
    db = get_database()
    now = datetime.now(timezone.utc)

    task_prompt = f"""Tu es un Scrum Master expert. Génère les tâches Sprint pour le projet '{project_name}'.

Spécification :
{spec_content[:3000]}

RÈGLES STRICTES :
- TOUT le texte en FRANÇAIS (titres, descriptions)
- NE PAS assigner de membres — assignee_ids doit toujours être []
- NE PAS inclure project_lead_id ni team_members dans la réponse
- Génère autant de tâches que nécessaire selon la complexité du projet

Pour chaque tâche :
- 'title': Titre court et descriptif EN FRANÇAIS (pas de "Task 1:", "Task 2:" etc.)
- 'description': Description détaillée EN FRANÇAIS
- 'is_deliverable': Boolean
- 'assignee_ids': [] (toujours vide, le manager assigne manuellement)
- 'priority': 'HIGH', 'MEDIUM', ou 'LOW'
- 'story_points': Entier (1, 2, 3, 5, 8 ou 13)
- 'days_to_deadline': Entier (jours depuis aujourd'hui)

Retourne UNIQUEMENT un objet JSON valide (sans markdown) :
{{
  "tasks": [
    {{
      "title": "Titre descriptif en français",
      "description": "Description détaillée en français",
      "is_deliverable": false,
      "assignee_ids": [],
      "priority": "HIGH",
      "story_points": 5,
      "days_to_deadline": 14
    }}
  ]
}}
"""

    try:
        assign_res = await decision_agent.llm.ainvoke([
            SystemMessage(content=decision_agent.system_prompt),
            HumanMessage(content=task_prompt)
        ])
    except Exception as e:
        print(f"ERROR: Decision agent failed: {str(e)}")
        raise e

    final_data = {"tasks": []}
    try:
        obj_match = re.search(r'\{.*\}', assign_res.content, re.DOTALL)
        if obj_match:
            final_data = json.loads(obj_match.group())
    except Exception as e:
        print(f"DEBUG: Failed to parse tasks JSON: {str(e)}")
        return "Failed to parse tasks generated by AI."

    tasks_data = final_data.get("tasks", [])

    formatted_tasks = []
    for t in tasks_data:
        days_to_deadline = t.get("days_to_deadline", 14)
        deadline = now + timedelta(days=days_to_deadline)
        formatted_task = {
            "title": t.get("title"),
            "description": t.get("description"),
            "assignee_ids": [],          # Always empty — manager assigns manually
            "priority": t.get("priority", "MEDIUM"),
            "story_points": t.get("story_points", 3),
            "is_deliverable": t.get("is_deliverable", False),
            "deadline": deadline,
            "project_id": project_id,
            "status": "TODO"             # All generated tasks start in TODO
        }
        formatted_tasks.append(formatted_task)

    if formatted_tasks:
        await db["tasks"].delete_many({"project_id": project_id})
        await create_project_tasks_func(project_id=project_id, tasks=formatted_tasks)

    return f"Successfully generated {len(formatted_tasks)} tasks (no auto-assignment)."


async def execute_project_initialization(project_idea: str):
    """
    Complex workflow to initialize a project.
    """
    db = get_database()
    project_idea_str: str = str(project_idea)
    print(f"DEBUG: Initializing project with idea: {project_idea_str[:50]}...")

    init_prompt = f"""Based on this project idea: {project_idea_str}
    Generate a PROFESSIONAL and COMPREHENSIVE Specification Book (Cahier des Charges) in Markdown.

    The document MUST include:
    1. **Project Overview**: Mission, goals, and target audience.
    2. **Functional Requirements**: Detailed features and user stories.
    3. **Technical Architecture**: System components, tech stack choice, and data flow.
    4. **Mermaid Diagrams**:
       - A **Use Case Diagram** showing interactions between actors and the system.
       - A **Flowchart/Sequence Diagram** for the main logic.
       *STRICT MERMAID RULES*:
       - ALWAYS use `flowchart TD`.
       - NEVER use `|text|>` or `|text|>`. Use ONLY `-->|text| B` or `--> B`.
       - Example of valid syntax: `A[User] -->|login| B[Auth System]`
       - Do NOT use special characters inside labels. Use ONLY simple text.
    5. **Data Model**: Key entities and their relationships.
    6. **Non-Functional Requirements**: Security, performance, and scalability.
    7. **Methodology**: Details on the Scrum implementation for this specific project.

    Also generate:
    - 4-5 key Milestones (JSON format: [{{"title": "...", "days_from_now": int}}]).
    - A detailed Backup Plan (Markdown) for risk mitigation.
    - Metadata (JSON format: {{"project_name": "A short professional name", "current_risk": "One line describing main risk"}}).

    Return the response in this EXACT format:
    ---SPEC---
    (detailed markdown specification)
    ---MILESTONES---
    (JSON list)
    ---BACKUP---
    (markdown)
    ---METADATA---
    (JSON block)
    """

    try:
        res = await planning_agent.llm.ainvoke([
            SystemMessage(content=planning_agent.system_prompt),
            HumanMessage(content=init_prompt)
        ], temperature=0)
        print("DEBUG: Planning agent responded.")
    except Exception as e:
        print(f"ERROR: Planning agent failed: {str(e)}")
        raise e

    content = res.content
    spec_content = ""
    milestones_json = "[]"
    backup_content = ""
    metadata_json = "{}"

    if "---SPEC---" in content:
        parts = content.split("---SPEC---")[1].split("---MILESTONES---")
        spec_content = parts[0].strip()
        if len(parts) > 1:
            sub_parts = parts[1].split("---BACKUP---")
            milestones_json = sub_parts[0].strip()
            if len(sub_parts) > 1:
                meta_parts = sub_parts[1].split("---METADATA---")
                backup_content = meta_parts[0].strip()
                if len(meta_parts) > 1:
                    metadata_json = meta_parts[1].strip()
    else:
        spec_content = content

    milestones_data = []
    try:
        m_match = re.search(r'\[.*\]', milestones_json, re.DOTALL)
        if m_match:
            milestones_data = json.loads(m_match.group())
    except Exception:
        milestones_data = []

    milestones = []
    now = datetime.now(timezone.utc)
    for m in milestones_data:
        milestones.append({
            "title": m.get("title", "Milestone"),
            "date": now + timedelta(days=m.get("days_from_now", 30))
        })

    metadata_data = {}
    try:
        meta_match = re.search(r'\{.*\}', metadata_json, re.DOTALL)
        if meta_match:
            metadata_data = json.loads(meta_match.group())
    except Exception:
        metadata_data = {}

    name_snippet = metadata_data.get("project_name")
    if not name_snippet or len(name_snippet) < 3:
        name_snippet = project_idea_str[0:50].strip()

    current_risk = metadata_data.get("current_risk", "Pending initial assessment")
    readable_id = "PRJ-" + "".join(random.choices(string.ascii_uppercase + string.digits, k=4))

    proj_doc = {
        "name": name_snippet,
        "description": project_idea_str[0:500],
        "status": "ON_TRACK",
        "progress_percentage": 0,
        "timeline_start": now,
        "timeline_end": now + timedelta(days=90),
        "milestones": milestones,
        "backup_plan": backup_content,
        "created_at": now,
        "team_members": [],          # Empty — manager fills manually
        "readable_id": readable_id,
        "current_risk": current_risk
    }

    proj_result = await db["projects"].insert_one(proj_doc)
    project_id = str(proj_result.inserted_id)

    await create_specification_book_func(
        project_title=name_snippet,
        project_summary=project_idea_str[0:200],
        markdown_content=spec_content,
        project_id=project_id
    )

    activity = {
        "type": "PROJECT_CREATED",
        "entity_id": project_id,
        "entity_name": name_snippet,
        "user_id": "AI_SYSTEM",
        "user_name": "AI Orchestrator",
        "details": "Project initialized via AI workflow",
        "created_at": now
    }
    await db["activities"].insert_one(activity)

    result_msg = await generate_and_assign_tasks(project_id, str(name_snippet), spec_content)

    return f"Project '{name_snippet}' initialized. {result_msg}"


async def reassign_project_tasks(project_id: str):
    """
    Kept for compatibility — does nothing now since assignment is manual.
    """
    return "Assignment is done manually by the manager in Kanban."
