from .planning_agent import planning_agent
from .decision_agent import decision_agent
from .tools import (
    create_specification_book_func, 
    list_team_members_func, 
    create_project_tasks_func, 
    send_notification_func
)
from langchain_core.messages import HumanMessage, SystemMessage
from app.core.db import get_database
from datetime import datetime, timedelta, timezone
from bson import ObjectId
import json
import re
import traceback
import random
import string

async def generate_and_assign_tasks(project_id: str, project_name: str, spec_content: str):
    """
    Generate tasks in French based on a specification book.
    No member assignment — the manager assigns manually in Kanban.
    """
    db = get_database()
    now = datetime.now(timezone.utc)

    task_prompt = f"""Tu es un Scrum Master expert. Génère les tâches Sprint pour le projet '{project_name}'.

Spécification :
{spec_content[:3000]}

RÈGLES STRICTES :
- TOUT le texte en FRANÇAIS (titre, description, priorité en anglais uniquement : HIGH/MEDIUM/LOW)
- NE PAS assigner de membres (assignee_ids doit être une liste vide [])
- NE PAS inclure project_lead_id ni team_members
- Génère autant de tâches que nécessaire selon la complexité

Pour chaque tâche :
- 'title': Titre court et descriptif EN FRANÇAIS
- 'description': Description détaillée EN FRANÇAIS
- 'is_deliverable': Boolean
- 'assignee_ids': [] (toujours vide)
- 'priority': 'HIGH', 'MEDIUM', ou 'LOW'
- 'story_points': Entier (1, 2, 3, 5, 8 ou 13)
- 'days_to_deadline': Entier (jours depuis aujourd'hui)

Retourne UNIQUEMENT un objet JSON valide (sans markdown) :
{{
  "tasks": [
    {{
      "title": "Titre en français",
      "description": "Description en français",
      "is_deliverable": false,
      "assignee_ids": [],
      "priority": "HIGH",
      "story_points": 5,
      "days_to_deadline": 14
    }}
  ]
}}
"""

    try:
        assign_res = await decision_agent.llm.ainvoke([
            SystemMessage(content=decision_agent.system_prompt),
            HumanMessage(content=task_prompt)
        ])
    except Exception as e:
        print(f"ERROR: Decision agent failed: {str(e)}")
        raise e

    final_data = {"tasks": []}
    try:
        obj_match = re.search(r'\{.*\}', assign_res.content, re.DOTALL)
        if obj_match:
            final_data = json.loads(obj_match.group())
    except Exception as e:
        print(f"DEBUG: Failed to parse tasks JSON: {str(e)}")
        return "Failed to parse tasks generated by AI."

    tasks_data = final_data.get("tasks", [])

    # Save Tasks — no assignments, no team_members update
    formatted_tasks = []
    for t in tasks_data:
        days_to_deadline = t.get("days_to_deadline", 14)
        deadline = now + timedelta(days=days_to_deadline)

        formatted_task = {
            "title": t.get("title"),
            "description": t.get("description"),
            "assignee_ids": [],  # Manager assigns manually
            "priority": t.get("priority", "MEDIUM"),
            "story_points": t.get("story_points", 3),
            "is_deliverable": t.get("is_deliverable", False),
            "deadline": deadline,
            "project_id": project_id,
            "status": "BACKLOG"
        }
        formatted_tasks.append(formatted_task)

    if formatted_tasks:
        await db["tasks"].delete_many({"project_id": project_id})
        await create_project_tasks_func(project_id=project_id, tasks=formatted_tasks)

    return f"Successfully generated {len(formatted_tasks)} tasks (no auto-assignment)."

async def execute_project_initialization(project_idea: str):
    """
    Complex workflow to initialize a project.
    """
    db = get_database()
    project_idea_str: str = str(project_idea)
    print(f"DEBUG: Initializing project with idea: {project_idea_str[:50]}...")
    
    # 1. Generate Specification, Milestones, and Backup Plan
    init_prompt = f"""Based on this project idea: {project_idea_str}
    Generate:
    1. A comprehensive Specification Book (Markdown).
       Include detailed System Architecture, a Use Case Diagram (Mermaid syntax), and a Sequence Diagram for the main user flow (Mermaid syntax).
    2. A list of 3-4 key Milestones (JSON format: [{{"title": "...", "days_from_now": int}}]).
    3. A brief Backup Plan (Markdown).
    4. Metadata for the project (JSON format: {{"project_name": "A short professional name", "current_risk": "One line describing main risk or problem"}}).
    
    Return the response in this EXACT format and ensure all 4 sections are present:
    ---SPEC---
    (markdown)
    ---MILESTONES---
    (JSON list)
    ---BACKUP---
    (markdown)
    ---METADATA---
    (JSON block)
    """
    
    try:
        res = await planning_agent.llm.ainvoke([
            SystemMessage(content=planning_agent.system_prompt),
            HumanMessage(content=init_prompt)
        ], temperature=0) # Use 0 for more reliable formatting
        print("DEBUG: Planning agent responded.")
    except Exception as e:
        print(f"ERROR: Planning agent failed: {str(e)}")
        raise e
    
    content = res.content
    spec_content = ""
    milestones_json = "[]"
    backup_content = ""
    metadata_json = "{}"
    
    if "---SPEC---" in content:
        parts = content.split("---SPEC---")[1].split("---MILESTONES---")
        spec_content = parts[0].strip()
        if len(parts) > 1:
            sub_parts = parts[1].split("---BACKUP---")
            milestones_json = sub_parts[0].strip()
            if len(sub_parts) > 1:
                meta_parts = sub_parts[1].split("---METADATA---")
                backup_content = meta_parts[0].strip()
                if len(meta_parts) > 1:
                    metadata_json = meta_parts[1].strip()
    else:
        spec_content = content
        
    milestones_data = []
    try:
        m_match = re.search(r'\[.*\]', milestones_json, re.DOTALL)
        if m_match:
            milestones_data = json.loads(m_match.group())
    except Exception as e:
        milestones_data = []

    milestones = []
    now = datetime.now(timezone.utc)
    for m in milestones_data:
        milestones.append({
            "title": m.get("title", "Milestone"),
            "date": now + timedelta(days=m.get("days_from_now", 30))
        })

    metadata_data = {}
    try:
        meta_match = re.search(r'\{.*\}', metadata_json, re.DOTALL)
        if meta_match:
            metadata_data = json.loads(meta_match.group())
    except Exception as e:
        metadata_data = {}

    # 3. Create Project
    name_snippet = metadata_data.get("project_name")
    if not name_snippet or len(name_snippet) < 3:
        name_snippet = project_idea_str[0:50].strip()
        
    current_risk = metadata_data.get("current_risk", "Pending initial assessment")
    readable_id = "PRJ-" + "".join(random.choices(string.ascii_uppercase + string.digits, k=4))

    proj_doc = {
        "name": name_snippet,
        "description": project_idea_str[0:500],
        "status": "ON_TRACK",
        "progress_percentage": 0,
        "timeline_start": now,
        "timeline_end": now + timedelta(days=90),
        "milestones": milestones,
        "backup_plan": backup_content,
        "created_at": now,
        "team_members": [],
        "readable_id": readable_id,
        "current_risk": current_risk
    }
    
    proj_result = await db["projects"].insert_one(proj_doc)
    project_id = str(proj_result.inserted_id)
    
    await create_specification_book_func(
        project_title=name_snippet,
        project_summary=project_idea_str[0:200],
        markdown_content=spec_content,
        project_id=project_id
    )

    # Log activity for project creation
    activity = {
        "type": "PROJECT_CREATED",
        "entity_id": project_id,
        "entity_name": name_snippet,
        "user_id": "AI_SYSTEM",
        "user_name": "AI Orchestrator",
        "details": "Project initialized via AI workflow",
        "created_at": now
    }
    await db["activities"].insert_one(activity)

    # 4. Generate & Assign Tasks (Using the new reusable function)
    result_msg = await generate_and_assign_tasks(project_id, str(name_snippet), spec_content)
    
    return f"Project '{name_snippet}' initialized. {result_msg}"

async def reassign_project_tasks(project_id: str):
    """
    Reassigns unassigned tasks for an existing project using AI.
    """
    db = get_database()
    project = await db["projects"].find_one({"_id": ObjectId(project_id)})
    if not project:
        return "Project not found."

    # Identify unassigned tasks
    tasks = await db["tasks"].find({"project_id": project_id, "assignee_ids": {"$in": [None, []]}}).to_list(length=None)
    if not tasks:
        return "No unassigned tasks found for this project."

    # List current members
    members_report = await list_team_members_func()

    # Create a simplified task list for the prompt
    tasks_simplified = []
    for t in tasks:
        tasks_simplified.append(f"Task ID: {str(t['_id'])}\nTitle: {t.get('title')}\nDescription: {t.get('description')}\n---\n")
    tasks_text = "".join(tasks_simplified)

    task_prompt = f"""You are a Scrum Master responsible for FAIR and BALANCED task distribution.
Below are unassigned tasks for project '{project.get('name')}'.

Tasks:
{tasks_text}

Available members and their skills (use their EXACT IDs):
{members_report}

=== STRICT DISTRIBUTION RULES ===
1. DISTRIBUTE TASKS FAIRLY: Every member must receive at least one task if possible.
2. BALANCE WORKLOAD: Spread the tasks as evenly as possible across all members.
3. SKILL MATCHING: Prefer matching skills, but assign simpler tasks to members without listed skills.
4. NO MONOPOLY: No single member should receive more than 40% of all tasks.
5. USE REAL IDs: Always use the exact MongoDB user IDs listed above.

Return ONLY a valid JSON object (no markdown, no explanation):
{{
  "assignments": [
    {{
      "task_id": "<task_id>",
      "assignee_ids": ["<member_id>"]
    }}
  ]
}}
"""

    try:
        assign_res = await decision_agent.llm.ainvoke([
            SystemMessage(content=decision_agent.system_prompt),
            HumanMessage(content=task_prompt)
        ])
    except Exception as e:
        print(f"ERROR: Decision agent failed: {str(e)}")
        raise e

    final_data = { "assignments": [] }
    try:
        obj_match = re.search(r'\{.*\}', assign_res.content, re.DOTALL)
        if obj_match:
            final_data = json.loads(obj_match.group())
    except Exception as e:
        print(f"DEBUG: Failed to parse reassignments JSON: {str(e)}")
        return "Failed to parse reassignments generated by AI."

    assignments = final_data.get("assignments", [])
    updates_count = 0
    assigned_users = set()

    for a in assignments:
        t_id = a.get("task_id")
        a_ids = a.get("assignee_ids", [])
        if t_id and a_ids and ObjectId.is_valid(t_id):
            await db["tasks"].update_one(
                {"_id": ObjectId(t_id)},
                {"$set": {"assignee_ids": a_ids, "status": "TODO"}}
            )
            updates_count += 1
            assigned_users.update(a_ids)

    # Update project team members with newly assigned users
    if assigned_users:
        current_members = project.get("team_members", [])
        new_members = list(set(current_members) | assigned_users)
        await db["projects"].update_one(
            {"_id": ObjectId(project_id)},
            {"$set": {"team_members": new_members}}
        )

    return f"Successfully reassigned {updates_count} tasks to {len(assigned_users)} unique members."

